# Generated by Django 6.0.4 on 2026-05-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_remove_placeaccessibility_religious_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('religious_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.religiousplace')),
            ],
        ),
    ]
