# Generated by Django 6.0.4 on 2026-05-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placephoto',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
