# Generated by Django 6.0.4 on 2026-05-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_remove_placeaccessibility_religious_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='manual', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_info', to='places.religiousplace')),
            ],
        ),
    ]
