# Generated by Django 6.0.4 on 2026-04-09 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('religions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='religions.religion')),
            ],
        ),
    ]
