# Generated by Django 6.0.4 on 2026-04-09 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('denominations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReligiousPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_open_247', models.BooleanField(default=False)),
                ('opening_hours_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='denominations.denomination')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='manual', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_info', to='places.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('religious_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='places.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_wheelchair_access', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='places.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('religious_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='places.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('religious_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.religiousplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='places.religiousplace')),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='places_plac_latitud_0f4d55_idx')],
            },
        ),
    ]
