# Generated by Django 6.0.4 on 2026-05-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeaccessibility',
            name='religious_place',
        ),
        migrations.RemoveField(
            model_name='placecontact',
            name='religious_place',
        ),
        migrations.RemoveField(
            model_name='placephoto',
            name='religious_place',
        ),
        migrations.RemoveField(
            model_name='placesource',
            name='religious_place',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='religious_place',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
        migrations.DeleteModel(
            name='PlaceAccessibility',
        ),
        migrations.DeleteModel(
            name='PlaceContact',
        ),
        migrations.DeleteModel(
            name='PlacePhoto',
        ),
        migrations.DeleteModel(
            name='PlaceSource',
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
