# Generated by Django 6.0.3 on 2026-03-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_wheelchair_access', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='places.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='places.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='places.religiousplace')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='manual', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_info', to='places.religiousplace')),
            ],
        ),
    ]
