# Generated by Django 6.0.3 on 2026-03-28 14:31

from django.db import migrations

def forward(apps, schema_editor):
    ReligiousPlace = apps.get_model('places', 'ReligiousPlace')
    PlaceAddress = apps.get_model('places', 'PlaceAddress')
    PlaceContact = apps.get_model('places', 'PlaceContact')
    PlaceAccessibility = apps.get_model('places', 'PlaceAccessibility')
    PlaceSource = apps.get_model('places', 'PlaceSource')

    for place in ReligiousPlace.objects.all():
        # Создаём PlaceAddress
        PlaceAddress.objects.create(
            religious_place=place,
            address_line=place.address_line,
            city=place.city,
            postal_code=place.postal_code,
            latitude=place.latitude,
            longitude=place.longitude,
        )
        # Создаём PlaceContact
        PlaceContact.objects.create(
            religious_place=place,
            phone=place.phone,
            website=place.website,
        )
        # Создаём PlaceAccessibility
        PlaceAccessibility.objects.create(
            religious_place=place,
            has_wheelchair_access=place.has_wheelchair_access,
            has_parking=place.has_parking,
        )
        # Создаём PlaceSource
        PlaceSource.objects.create(
            religious_place=place,
            source=place.source,
            external_id=place.external_id,
        )

def reverse(apps, schema_editor):
    PlaceAddress = apps.get_model('places', 'PlaceAddress')
    PlaceContact = apps.get_model('places', 'PlaceContact')
    PlaceAccessibility = apps.get_model('places', 'PlaceAccessibility')
    PlaceSource = apps.get_model('places', 'PlaceSource')
    PlaceAddress.objects.all().delete()
    PlaceContact.objects.all().delete()
    PlaceAccessibility.objects.all().delete()
    PlaceSource.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeaccessibility_placeaddress_placecontact_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
