# Generated by Django 6.0.3 on 2026-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_placeaccessibility_religious_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='religiousplace',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='religiousplace',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
