# Generated by Django 6.0.3 on 2026-03-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20260328_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='religiousplace',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='city',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='has_wheelchair_access',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='source',
        ),
        migrations.RemoveField(
            model_name='religiousplace',
            name='website',
        ),
    ]
