# Generated by Django 6.0.3 on 2026-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_religiousplace_address_line_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placeaddress',
            index=models.Index(fields=['latitude', 'longitude'], name='places_plac_latitud_0f4d55_idx'),
        ),
    ]
