# Generated by Django 6.0.4 on 2026-05-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_remove_placeaccessibility_religious_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_wheelchair_access', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('religious_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility', to='places.religiousplace')),
            ],
        ),
    ]
